package com.tourism.egypt.tourism_app.service;


import com.tourism.egypt.tourism_app.model.Owner;
import com.tourism.egypt.tourism_app.repository.OwnerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class OwnerService {

    @Autowired
    private OwnerRepository ownerRepository;

    public List<Owner> getAllOwners() {
        return ownerRepository.findAll();
    }

    public Owner getOwnerById(Long id) {
        return ownerRepository.findById(id).orElse(null);
    }

    public Owner createOwner(Owner owner) {
        return ownerRepository.save(owner);
    }

    public Owner updateOwner(Long id, Owner ownerDetails) {
        Optional<Owner> optionalOwner = ownerRepository.findById(id);
        if (optionalOwner.isPresent()) {
            Owner owner = optionalOwner.get();
            owner.setName(ownerDetails.getName()); // Ensure getName() is generated by Lombok
            owner.setEmail(ownerDetails.getEmail()); // Ensure getEmail() is generated by Lombok
            owner.setPassword(ownerDetails.getPassword()); // Ensure getPassword() is generated by Lombok
            return ownerRepository.save(owner);
        }
        return null;
    }

    public void deleteOwner(Long id) {
        ownerRepository.deleteById(id);
    }

    public Owner findByEmail(String email) {
        return ownerRepository.findByEmail(email);
    }
}